version: '3.8'
services:
  python-app:
    container_name: word-count
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_S3_API}:9000
      - ${MINIO_WEB_CONSOLE}:9001
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - ./data/minio:/data
  
  mc:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb local/word-count || true &&
      tail -f /dev/null
      "
